# Generated by Django 3.0.5 on 2020-05-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['name'], 'verbose_name_plural': "Car's"},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['house_no', 'landmark', 'address']},
        ),
        migrations.AlterModelOptions(
            name='passport',
            options={'ordering': ['passport_id'], 'verbose_name_plural': "Passport's"},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name'], 'verbose_name_plural': "Person's"},
        ),
        migrations.AlterField(
            model_name='passport',
            name='expire_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('O', 'Others'), ('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
    ]
